# Generated by Django 5.2.7 on 2025-10-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('technical_skills', models.JSONField(default=list, help_text='Technical skills extracted from CV')),
                ('soft_skills', models.JSONField(default=list, help_text='Soft skills extracted from CV')),
                ('languages', models.JSONField(default=list, help_text='Languages and proficiency levels')),
                ('certifications', models.JSONField(default=list, help_text='Certifications and credentials')),
                ('total_experience_years', models.FloatField(default=0.0)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('hired', 'Hired')], default='active', max_length=50)),
                ('availability', models.CharField(choices=[('immediate', 'Immediate'), ('2 weeks', '2 weeks notice'), ('1 month', '1 month notice'), ('3 months', '3+ months')], default='immediate', max_length=50)),
                ('cv_text', models.TextField(blank=True, help_text='Full text extracted from CV')),
                ('embedding', models.JSONField(default=list, help_text='768-dimensional embedding vector')),
                ('cv_metadata', models.JSONField(default=dict, help_text='Additional CV metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50)),
                ('remote_allowed', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('required_skills', models.JSONField(default=list)),
                ('required_experience_years', models.IntegerField(default=0)),
                ('required_education', models.CharField(blank=True, max_length=200)),
                ('embedding', models.JSONField(default=list, help_text='768-dimensional embedding vector')),
                ('extracted_requirements', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=50)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Path to CV file in S3/MinIO', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC')], max_length=10)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('extraction_error', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted and structured CV data')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='smartrecruitai.candidate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='smartrecruitai.candidate')),
                ('job_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='smartrecruitai.joboffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.FloatField(help_text='Overall matching score (0-100)')),
                ('technical_skill_score', models.FloatField()),
                ('experience_score', models.FloatField()),
                ('education_score', models.FloatField()),
                ('soft_skill_score', models.FloatField()),
                ('match_explanation', models.TextField(help_text='AI-generated explanation of the match')),
                ('strengths', models.JSONField(default=list, help_text="Candidate's strengths for this role")),
                ('gaps', models.JSONField(default=list, help_text='Gaps or concerns')),
                ('recommendations', models.JSONField(default=list, help_text='Recommendations for hiring decision')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='smartrecruitai.candidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='smartrecruitai.joboffer')),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('candidate', 'job_offer')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('contact_email', 'Contact Email'), ('interview_questions', 'Interview Questions'), ('candidate_summary', 'Candidate Summary'), ('report', 'Analysis Report')], max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartrecruitai.candidate')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartrecruitai.joboffer')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartrecruitai.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartrecruitai.candidate')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartrecruitai.joboffer')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartrecruitai.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources_used', models.JSONField(default=list, help_text='Sources referenced by RAG')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='smartrecruitai.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='smartrecruitai.recruiter'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='smartrecruitai.recruiter'),
        ),
    ]
