# Generated by Django 5.2.7 on 2025-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrecruitai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, help_text='Will be extracted from CV', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, help_text='Will be extracted from CV', max_length=200),
        ),
    ]
