# Generated by Django 5.2.7 on 2025-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrecruitai', '0002_alter_candidate_email_alter_candidate_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='overall_score',
            field=models.FloatField(default=0.0, help_text='Overall matching score (0-100)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='soft_skill_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='technical_skill_score',
            field=models.FloatField(default=0.0),
        ),
    ]
