# Generated by Django 5.2.7 on 2025-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrecruitai', '0003_alter_match_education_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_explanation',
            field=models.TextField(blank=True, help_text='AI-generated explanation of the match'),
        ),
    ]
