# Generated by Django 5.2.7 on 2025-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrecruitai', '0004_alter_match_match_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gitlab_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_urls',
            field=models.JSONField(default=list, help_text='Portfolio and personal website URLs'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_links',
            field=models.JSONField(default=dict, help_text='All extracted professional links organized by type'),
        ),
    ]
